export const PROFILE_DATA = 'PROFILE_DATA';
export const MODAL_STATE = 'MODAL_STATE';
export const SUBMENU_STATE = 'SUBMENU_STATE';
export const CHATBOT_STATE = 'CHATBOT_STATE';
export const MOBILE_MENU_STATE = 'MOBILE_MENU_STATE';